apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: tobybeenation.com
      http:
        paths:
          - backend:
              serviceName: hello-world-service
              servicePort: 80